[build-system]
requires = ["setuptools >= 69.5.1", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "AnalysisOverflow"
dependencies = [
    "mlxtend>=0.23.1",
    "pandas>=2.2.2",
    "StackAPI>=0.3.0",
]
